=== natypr/training-web/3-xml-parser/data/schemeXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.com/medicines"
	xmlns:tns="http://www.example.com/medicines"
	elementFormDefault="qualified">

	<element name="medicines">
		<complexType>
			<sequence>
				<element name="medicine" type="tns:Medicine" minOccurs="1" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>


	<complexType name="Medicine">
 		<sequence>
			<element name="name" type="tns:Correct-string"/>
			<element name="pharm" type="tns:Correct-string"/>
			<element name="analogs" type="tns:Correct-string" minOccurs="0" maxOccurs="unbounded"/>
			<element name="manufacturer" type="tns:Manufacturer"/>
 		</sequence>
		<attribute name="id" type="tns:Id" use="required"/>
		<attribute name="group" type="tns:Group" use="optional"/>
	</complexType>


	<simpleType name="Id">
		<restriction base="string">
			<pattern value="[A-Za-z]\d{6}"/>
		</restriction>
	</simpleType>

	<simpleType name="Correct-string">
        <restriction base="string">
        	<pattern value="[a-zA-Z]{2,30}"/>
        </restriction>
    </simpleType>

	<simpleType name="Group">
		<restriction base="string">
			<enumeration value="antibiotic"/>
			<enumeration value="sedative"/>
			<enumeration value="vitamin"/>
		</restriction>
	</simpleType>


	<complexType name="Manufacturer">
		<sequence>
			<element name="certificate" type="tns:Certificate"/>
			<element name="packages" type="tns:Packages"/>
			<element name="dosage" type="tns:Dosage" />
		</sequence>
		<attribute name="versionn" type="tns:Versionn" use="required" default="tablets"/>
	</complexType>

	<simpleType name="Versionn">
		<restriction base="string">
			<enumeration value="tablets"/>
			<enumeration value="drops"/>
		</restriction>
	</simpleType>

	<complexType name="Certificate">
		<attribute name="number" type="positiveInteger" use="required"/>
		<attribute name="issue-date" type="date" use="required"/>
		<attribute name="expiration-date" type="date" use="required"/>
		<attribute name="reg-organization" type="tns:Correct-string" use="required"/>
	</complexType>

	<complexType name="Packages">
		<attribute name="quantity-in-package" type="positiveInteger" use="required"/>
		<attribute name="price" type="positiveInteger" use="required"/>
	</complexType>

	<complexType name="Dosage">
		<attribute name="quantity-per-day" type="positiveInteger" use="required"/>
		<attribute name="period-of-use-day" type="positiveInteger" use="required"/>
	</complexType>

</schema>

=== natypr/training-web/3-xml-parser/src/main/resources/schemeXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/medicines"
        xsi:schemaLocation="http://www.example.com/medicines schemeXSD.xsd">

    <medicine id="A100000" group="antibiotic">
        <name>Analgin</name>
        <pharm>Belmedpreparaty</pharm> 
        <analogs>Andipal</analogs>   <!--  Nebagin  Realgin  -->
        <manufacturer version="tablets">
            <certificate number="12" issue-date="2016-11-30" expiration-date="2021-11-30"
                         reg-organization="Ozonepharm"/>
            <packages price="105" quantity-in-package="20"/>
            <dosage quantity-per-day="3" period-of-use-day="90"/>
        </manufacturer>
    </medicine>

    <medicine id="Z100001">
        <name>Hematogen</name>
        <pharm>Exon</pharm> 
        <manufacturer version="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

</medicines>

=== natypr/training-web/3-xml-parser/data/schemeXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/medicines"
        xsi:schemaLocation="http://www.example.com/medicines schemeXSD.xsd">

    <medicine id="A100000" group="antibiotic">
        <name>Analgin</name>
        <pharm>Belmedpreparaty</pharm> 
        <analogs>Andipal</analogs>
        <manufacturer versionn="tablets">
            <certificate number="12" issue-date="2016-11-30" expiration-date="2021-11-30"
                         reg-organization="Ozonepharm"/>
            <packages price="105" quantity-in-package="20"/>
            <dosage quantity-per-day="3" period-of-use-day="90"/>
        </manufacturer>
    </medicine>

    <medicine group="antibiotic" id="B100541">
        <name>Hematogen</name>
        <pharm>Exon</pharm> 
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="C102001">
        <name>Nuritan</name>
        <pharm>Vern</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="D300001" group="sedative">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="R230001" group="antibiotic">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="E435001" group="sedative">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="U103201">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="Q140001" group="vitamin">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="O104001">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="I100901" group="sedative">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="P100078" group="vitamin">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="J100991">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="S103401" group="vitamin">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="Z999001">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="G100031" group="vitamin">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

    <medicine id="W132001" group="vitamin">
        <name>Hematogen</name>
        <pharm>Exon</pharm>
        <manufacturer versionn="tablets">
            <certificate number="28" issue-date="2018-10-19" expiration-date="2022-04-15"
                         reg-organization="Lecpharm"/>
            <packages price="50" quantity-in-package="4"/>
            <dosage quantity-per-day="4" period-of-use-day="10"/>
        </manufacturer>
    </medicine>

</medicines>
